### PR TITLE
Update HTML/CSS/JS

### PR DESCRIPTION
**Pull request by dnhn**
Hello Trung, I have made some improvements on your portfolio, please check the codes!

HTML
- Update Meta tags
- Combined Google Fonts into one hyperlink
- Optimised tags for styling

LESS/CSS
- Updated Responsive design
- Elements spacing
- Corrected indentation
- Built new CSS from source using Koala

JS
- Fix quotes consistency

### CODE REVIEW

**Comment by trungvose** [comment]
Hello Nhan,

Thank you so much for your contribution. Let me take a review first and inform you asap. 
Seem I need to resolve some code conflicts first.

**Comment by trungvose** [comment]
I have already merged it Nhan. Thanks

Where did you see my portfolio ? :+1:

**Comment by dnhn** [comment]
@trungk18: I was wondering around on LinkedIn and saw you posted the link. Then thought I need to do something with this site :)

**Comment by trungvose** [comment]
Thank you so much.

Please add me on skype: trungk18 for further discussion.

Are you doing freelance at this moment ?

**Pull request merged**
